=== AdrashaVaux/cboe/rsrc/schemas/dialog.dtd
<!ELEMENT dialog ((field | text | pict | button | led | group | stack)*)>
<!ELEMENT field EMPTY>
<!ELEMENT br EMPTY>
<!ELEMENT text (#PCDATA|br)*>
<!ELEMENT pict EMPTY>
<!ELEMENT key EMPTY>
<!ELEMENT button (#PCDATA|key)*>
<!ELEMENT led (CDATA)>
<!ELEMENT group (led+)>
<!ELEMENT stack ((field | text | pict | button | led | group)*)>

<!ENTITY % num '(NUMBER)'>
<!ENTITY % bool '(true|false)'>
<!ENTITY % picttype '(blank|ter|teranim|monst|dlog|talk|scen|item|pc|field|boom|missile|full|map|status)'>
<!ENTITY % btntype '(small|regular|large|help|left|right|up|down|tiny|done|tall|trait|push)'>
<!ENTITY % letter 'a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z'>
<!ENTITY % mod 'ctrl|shift|alt'>
<!ENTITY % key '%mod;|%letter;|left|right|up|down|esc|enter|return|tab|help|space'>
<!ENTITY % rect '
	top			%num;						#REQUIRED
	left		%num;						#REQUIRED
	width		%num;						#IMPLIED
	height		%num;						#IMPLIED
'>
<!ENTITY % font "
	font		(dungeon|geneva|silom|maidenword)	'silom'
	size		(small|large)				'small'
	color		CDATA						#IMPLIED
	colour		CDATA						#IMPLIED
">

<!ATTLIST dialog
	skin		(light|dark)				'dark'
	debug		%bool;						'false'
	fore		CDATA						'black'
	defbtn		IDREF						#IMPLIED
>
<!ATTLIST field
	name		ID							#IMPLIED
	type		(num|text)					'text'
	%rect;
>
<!ATTLIST text
	name		ID							#IMPLIED
	framed		%bool;						'true'
	%font;
	def-key		(%key;|none)				'none'
	clickable	%bool;						'false'
	fromlist	(none|CDATA)				'none'
	%rect;
>
<!ATTLIST pict
	name		ID							#IMPLIED
	type		%picttype;					#REQUIRED
	custom		%bool;						'false'
	size		(small|wide|tall|large)		#IMPLIED
	def-key		(%key;|none)				'none'
	clickable	%bool;						'false'
	num			%num;						#REQUIRED
	%rect;
>
<!ATTLIST button
	name		ID							#REQUIRED
	type		%btntype;					#REQUIRED
	wrap		%bool;						'false'
	def-key		(%key;|none)				'none'
	fromlist	(none|CDATA)				'none'
	%rect;
>
<!ATTLIST led
	name		ID							#IMPLIED
	state		(red|green|off)				'off'
	fromlist	(none|CDATA)				'none'
	%rect;
	%font;
>
<!ATTLIST group
	name		ID							#IMPLIED
	fromlist 	(none|CDATA)				'none'
>
<!ATTLIST stack
	name		ID							#IMPLIED
>

=== AdrashaVaux/cboe/rsrc/dialogs/monster-info.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<?xml-stylesheet href="dialog.xsl" type="text/xsl"?>
<!--<!DOCTYPE dialog SYSTEM	"dialog.dtd">-->
<dialog skin='dark' defbtn='done'>
	<text size='large' top='209' left='21' width='137' height='16'>Immunities:</text>
	<text size='large' top='7' left='54' width='106' height='16'>Monster Info:</text>
	<button name='done' type='done' top='319' left='249'/>
	<pict name='pic' type='monst' num='0' top='8' left='12'/>
	<text name='name' framed='true' top='32' left='104' width='195' height='16'/>
	<text name='lvl' framed='true' top='59' left='53' width='25' height='16'/>
	<text name='hp' framed='true' top='59' left='134' width='47' height='16'/>
	<text name='sp' framed='true' top='59' left='258' width='47' height='16'/>
	<text name='def' framed='true' top='85' left='57' width='25' height='16'/>
	<text name='skill' framed='true' top='85' left='127' width='25' height='16'/>
	<text name='morale' framed='true' top='85' left='205' width='32' height='16'/>
	<text name='ap' framed='true' top='85' left='280' width='25' height='16'/>
	<text name='attack1' framed='true' top='111' left='63' width='44' height='16'/>
	<text name='attack2' framed='true' top='111' left='160' width='44' height='16'/>
	<text name='attack3' framed='true' top='111' left='261' width='44' height='16'/>
	<text name='mage' framed='true' top='137' left='78' width='25' height='17'/>
	<text name='priest' framed='true' top='137' left='188' width='25' height='17'/>
	<text name='poison' framed='true' top='137' left='280' width='25' height='17'/>
	<text name='abil1' framed='true' top='165' left='67' width='238' height='16'/>
	<led name='immune1' state='off' top='227' left='118'/>
	<led name='immune2' state='off' top='242' left='118'/>
	<led name='immune3' state='off' top='257' left='118'/>
	<led name='immune4' state='off' top='272' left='118'/>
	<led name='immune5' state='off' top='227' left='241'/>
	<led name='immune6' state='off' top='242' left='241'/>
	<led name='immune7' state='off' top='257' left='241'/>
	<led name='immune8' state='off' top='272' left='241'/>
	<button name='left' type='left' def-key='left' top='319' left='11'/>
	<button name='right' type='right' def-key='right' top='319' left='74'/>
	<text top='288' left='10' width='305' height='28'>(To make monsters appear in roster menu, cast Scry Monster on them.)</text>
	<text name='abil2' framed='true' top='188' left='67' width='238' height='16'/>
</dialog>

=== AdrashaVaux/cboe/osx/dialogxml/edit-terrain.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<?xml-stylesheet href="dialog.xsl" type="text/xsl"?>
<!DOCTYPE dialog SYSTEM	"dialog.dtd">
<dialog skin='light' fore='black' debug='true'>
	<text size='large' top='6' left='50' height='17' width='138'>Edit Terrain Type</text>
	<pict name='graphic' type='ter' num='0' top='8' left='8'/>
	<text top='8' left='222' height='14' width='111'>Terrain number:</text>
	<text name='number' top='8' left='340' height='14' width='37'>*num</text>
	<text top='31' left='50' height='14' width='120'>Terrain type name:</text>
	<field name='name' top='30'  left='186' height='16' width='186'/>
	<text top='63' left='9' height='14' width='120'>Terrain picture:</text>
	<field name='pict' top='62'  left='141' height='16' width='52' />
	<button name='pickpict' type='large' top='59' left='205'>Pick Picture</button>
	<button name='pickanim' type='large' top='59' left='319'>Animated</button>
	<text top='90' left='8' height='14' width='120'>Terrain blockage:</text>
	<group name='blockage'>
		<led name='clear' top='90' left='132' state='off' width='120'>Clear</led>
		<led name='curtain' top='107' left='132' state='off' width='120'>Walk through, opaque</led>
		<led name='special' top='124' left='132' state='off' width='120'>Clear, special</led>
		<led name='window' top='90' left='293' state='off' width='120'>Clear, blocked</led>
		<led name='obstructed' top='107' left='293' state='off' width='120'>Blocked, obstructed</led>
		<led name='opaque' top='124' left='293' state='off' width='120'>Blocked, opaque</led>
	</group>
	<led name='flight' top='150' left='26' state='off' width='120' font='silom'>Can fly over?</led>
	<led name='boat' top='150' left='154' state='off' width='120' font='silom'>Can boat over?</led>
	<led name='horse' top='150' left='307' state='off' width='120' font='silom'>Blocked to horses?</led>
	<text top='165' left='8' height='14' width='91'>Step sound:</text>
	<group name='sound'>
		<led name="step" top='167' left='102' state='off' width='60'>Footstep</led>
		<led name="squish" top='167' left='186' state='off' width='60'>Squish</led>
		<led name="crunch" top='167' left='282' state='off' width='60'>Crunch</led>
		<led name="nosound" top='167' left='386' state='off' width='60'>Silence</led>
		<led name="splash" top='167' left='497' state='off' width='60'>Big Splash</led>
	</group>
	<text top='194' left='8' height='14' width='91'>Shortcut key:</text>
	<field name='key' top='193' left='109' height='16' width='52' />
	<text top='194' left='171' height='14' width='91'>Light radius:</text>
	<field name='light' top='193' left='271' height='16' width='52' />
	<text top='193' left='333' height='14' width='128'>Transform to what?</text>
	<field name='trans' top='193' left='467' height='16' width='52' />
	
	<text top='217' left='8' height='14' width='91'>Ground type:</text>
	<field name='ground' top='216' left='109' height='16' width='52' />
	<text top='217' left='171' height='14' width='91'>Trim terrain:</text>
	<field name='trimter' top='216' left='271' height='16' width='52' />
	<text top='217' left='333' height='14' width='128'>Trim type:</text>
	<field name='trim' top='216' left='467' height='16' width='52' />
	<button name='picktrim' top='213' left='530' type='regular'>Choose</button>
	
	<text size='large' top='238' left='8' height='14' width='175'>Special properties:</text>
	<group name="prop">
		<led name='0' top='254' left='8' state='off' width='116'>None</led>
		<led name='1' top='269' left='8' state='off' width='116'>Change when step on</led>
		<led name='2' top='284' left='8' state='off' width='116'>Damaging terrain</led>
		<led name='3' top='299' left='8' state='off' width='116'>Is a bridge</led>
		<led name='4' top='314' left='8' state='off' width='116'>Change while occupied</led>
		<led name='5' top='329' left='8' state='off' width='116'>Dangerous terrain</led>
		<led name='6' top='344' left='8' state='off' width='116'>Reserved</led>
		<led name='7' top='359' left='8' state='off' width='116'>Crumbling terrain</led>
		<led name='8' top='254' left='146' state='off' width='116'>Lockable terrain</led>
		<led name='9' top='269' left='146' state='off' width='116'>Unlockable terrain</led>
		<led name='10' top='284' left='146' state='off' width='116'>Reserved</led>
		<led name='11' top='299' left='146' state='off' width='116'>Is a sign</led>
		<led name='12' top='314' left='146' state='off' width='116'>Call special when step</led>
		<led name='13' top='329' left='146' state='off' width='116'>Reserved</led>
		<led name='14' top='344' left='146' state='off' width='116'>Is a container</led>
		<led name='15' top='359' left='146' state='off' width='116'>Waterfall</led>
		<led name='16' top='254' left='285' state='off' width='116'>Conveyor belt</led>
		<led name='17' top='269' left='285' state='off' width='116'>Reserved</led>
		<led name='18' top='284' left='285' state='off' width='116'>Reserved</led>
		<led name='19' top='299' left='285' state='off' width='116'>Reserved</led>
		<led name='20' top='314' left='285' state='off' width='116'>Blocked to monsters</led>
		<led name='21' top='329' left='285' state='off' width='116'>Town entrance</led>
		<led name='22' top='344' left='285' state='off' width='116'>Change when used</led>
		<led name='23' top='359' left='285' state='off' width='116'>Call special when used</led>
	</group>
	<text top='385' left='9' height='14' width='91'>Extra values:</text>
	<text name='flag1text' framed='true' top='385' left='109' height='14' width='209'>*flag1</text>
	<field name='flag1' top='384' left='329' height='16' width='64' />
	<button name='pickflag1' top='381' left='404' type='regular'>Choose</button>
	<text name='flag2text' framed='true' top='410' left='109' height='14' width='209'>*flag2</text>
	<field name='flag2' top='409' left='329' height='16' width='64' />
	<button name='pickflag2' top='406' left='404' type='regular'>Choose</button>
	<text name='flag3text' framed='true' top='435' left='109' height='14' width='209'>*flag3</text>
	<field name='flag3' top='434' left='329' height='16' width='64' />
	<button name='pickflag3' top='431' left='404' type='regular'>Choose</button>
	
	<text top='254' left='467' height='14' width='100'>Combat Arena:</text>
	<field name='arena' top='275' left='467' height='16' width='64'/>
	<button name='pickarena' type='regular' top='299' left='467'>Choose</button>
	<button name='object' top='344' left='467' type='large'>Object Details</button>
	<text top='385' left='470' width='60' height='14'>Map icon:</text>
	<pict name='seemap' top='375' left='550' type='map' num='0'/>
	<field name='map' top='406' left='470' width='100' height='16'/>
	<button name='done' type='regular' def-key='enter' top='455' left='517'>OK</button>
	<button name='cancel' type='regular' def-key='esc' top='455' left='451'>Cancel</button>
	<button name='left' type='left' def-key='left' top='455' left='11'/>
	<button name='right' type='right' def-key='right' top='455' left='74'/>
	<text top='7' left='451' height='131' width='137'>Enter properties for this terrain type. For a detailed description of the fields, see the documentation. Note that, for terrain types 90 and below, only changes to the picture and shortcut key will be recorded.</text>
	<button name='help' type='help' def-key='help' top='5' left='588'/>
</dialog>

=== AdrashaVaux/cboe/rsrc/dialogs/item-info.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<?xml-stylesheet href="dialog.xsl" type="text/xsl"?>
<!--<!DOCTYPE dialog SYSTEM	"dialog.dtd">-->
<dialog skin='dark' defbtn='done'>
	<pict name='pic' type='item' num='0' top='9' left='8'/>
	<text size='large' top='6' left='45' width='102'>Item Info:</text>
	<text name='name' framed='true' top='33' left='101' width='141' height='16'/>
	<text name='type' framed='true' top='61' left='58' width='141' height='16'/>
	<text name='val' framed='true' top='61' left='245' width='47' height='16'/>
	<text name='dmg' framed='true' top='89' left='58' width='25' height='15'/>
	<text name='bonus' framed='true' top='89' left='146' width='25' height='15'/>
	<text name='def' framed='true' top='89' left='231' width='25' height='15'/>
	<text name='enc' framed='true' top='117' left='65' width='25' height='16'/>
	<text name='use' framed='true' top='118' left='138' width='26' height='16'/>
	<text name='lvl' framed='true' top='118' left='255' width='25' height='16'/>
	<text name='abil' framed='true' top='168' left='61' width='230' height='16'/>
	<button name='done' type='done' top='191' left='228'/>
	<button name='left' type='left' def-key='left' top='191' left='84'/>
	<button name='right' type='right' def-key='right' top='191' left='153'/>
	<led name='id' state='off' top='8' left='213'/>
	<led name='magic' state='off' top='8' left='280'/>
	<!--
	 TODO: This originally had width=11 height=6; if it looks wrong in-game, try reverting to that
	 TODO: Reinstate item descriptions
	 -->
	<text size='large' top='192' left='8' width='0' height='0'>Description:</text>
	<text name='desc' framed='true' top='210' left='8' width='12' height='6'/>
	<text name='weight' framed='true' top='142' left='60' width='44' height='15'/>
	<!--
	 TODO: Add the labels to the XML definition
	 -->
</dialog>

=== AdrashaVaux/cboe/rsrc/dialogs/pc-alchemy-info.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<?xml-stylesheet href="dialog.xsl" type="text/xsl"?>
<!--<!DOCTYPE dialog SYSTEM	"dialog.dtd">-->
<dialog skin='dark' defbtn='done'>
	<text size='large' top='10' left='54' width='163' height='15'>Alchemy known:</text>
	<pict type='dlog' num='20' top='6' left='6'/>
	<button name='done' type='done' top='174' left='356'/>
	<led name='potion' state='off' top='33' left='217'/>
	<led name='potion' state='off' top='47' left='217'/>
	<led name='potion' state='off' top='61' left='217'/>
	<led name='potion' state='off' top='75' left='217'/>
	<led name='potion' state='off' top='89' left='217'/>
	<led name='potion' state='off' top='103' left='217'/>
	<led name='potion' state='off' top='117' left='217'/>
	<led name='potion' state='off' top='131' left='217'/>
	<led name='potion' state='off' top='145' left='217'/>
	<led name='potion' state='off' top='159' left='217'/>
	<led name='potion' state='off' top='33' left='402'/>
	<led name='potion' state='off' top='47' left='402'/>
	<led name='potion' state='off' top='61' left='402'/>
	<led name='potion' state='off' top='75' left='402'/>
	<led name='potion' state='off' top='89' left='402'/>
	<led name='potion' state='off' top='103' left='402'/>
	<led name='potion' state='off' top='117' left='402'/>
	<led name='potion' state='off' top='131' left='402'/>
	<led name='potion' state='off' top='145' left='402'/>
	<led name='potion' state='off' top='159' left='402'/>
	<!--
	 TODO: This originally had width=119; if it looks wrong in-game, try reverting to that
	 -->
	<text top='179' left='8' width='250' height='16'>Number in ( ) is minimum skill to make.</text>
</dialog>

=== AdrashaVaux/cboe/rsrc/dialogs/edit-item-abils.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<?xml-stylesheet href="dialog.xsl" type="text/xsl"?>
<!--<!DOCTYPE dialog SYSTEM	"dialog.dtd">-->
<dialog skin='light' defbtn='okay' debug='true'>
	<field name='str' top='88' left='183' width='77' height='16'/>
	<button name='okay' type='regular' top='266' left='471'>OK</button>
	<button name='cancel' type='regular' top='266' left='405' def-key='esc'>Cancel</button>
	<!--
	 NOTE: All these LEDs have been shifted 100 pixels left to account for the labels swapping sides
	 -->
	<group name='use-type'>
		<led name='use0' state='off' top='143' left='164' width='100'>Help using PC</led>
		<led name='use1' state='off' top='158' left='164' width='100'>Harm using PC</led>
		<led name='use2' state='off' top='173' left='164' width='100'>Help whole party</led>
		<led name='use3' state='off' top='188' left='164' width='100'>Harm whole party</led>
	</group>
	<led name='always-id' state='off' top='144' left='415' width='100'>Always identified</led>
	<led name='magic' state='off' top='159' left='415' width='100'>Magical</led>
	<led name='cursed' state='off' top='174' left='415' width='100'>Cursed</led>
	<led name='conceal' state='off' top='189' left='415' width='100'>Conceal ability</led>
	<pict type='dlog' num='16' top='8' left='11'/>
	<text size='large' top='6' left='50' width='158' height='16'>Edit Item Abilities</text>
	<text top='8' left='222' width='111' height='14'>Item number:</text>
	<text name='num' top='8' left='340' width='37' height='14'/>
	<button name='weapon' type='large' top='58' left='333'>Weapon Abil.</button>
	<text size='large' top='63' left='8' width='142' height='13'>Item special ability:</text>
	<text name='abilname' framed='true' top='63' left='161' width='163' height='13'/>
	<text top='17' left='486' width='45' height='14'/>
	<text top='84' left='8' width='168' height='27'>Ability strength: (Usually 0-10, see instructions)</text>
	<text top='140' left='8' width='135' height='13'>Item use properties</text>
	<text top='156' left='21' width='123' height='39'>Only used for item abilities which are used (like healing).</text>
	<text top='140' left='292' width='121' height='13'>Other properties:</text>
	<text top='209' left='10' width='155' height='42'>Item treasure class: (0 is lowest level of treasure, 4 is highest)</text>
	<!--
	 NOTE: All these LEDs have been shifted 100 pixels left to account for the labels swapping sides
	 -->
	<group name='treasure'>
		<led name='type0' state='off' top='213' left='208' width='140'>Type 0: Junk, Not left</led>
		<led name='type1' state='off' top='228' left='208' width='140'>Type 1: Lousy, 1 - 20 gp</led>
		<led name='type2' state='off' top='243' left='208' width='140'>Type 2: So-so, 20-200 gp</led>
		<led name='type3' state='off' top='258' left='208' width='140'>Type 2: Good, 200+ gp</led>
		<led name='type4' state='off' top='273' left='208' width='140'>Type 4: Greate, 2500+ gp</led>
	</group>
	<text top='25' left='50' width='145' height='14'>Current item name:</text>
	<text name='name' top='25' left='198' width='196' height='14'/>
	<text top='41' left='50' width='145' height='14'>Current item variety:</text>
	<text name='variety' top='41' left='198' width='196' height='14'/>
	<button name='general' type='large' top='57' left='441'>General Abil.</button>
	<button name='usable' type='large' top='83' left='333'>NonSpell Use</button>
	<button name='missile' type='large' top='107' left='441'>Missiles</button>
	<button name='reagent' type='large' top='108' left='333'>Reagents</button>
	<button name='spell' type='large' top='82' left='441'>Spell Usable</button>
</dialog>

=== AdrashaVaux/cboe/rsrc/dialogs/edit-monster-abils.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<?xml-stylesheet href="dialog.xsl" type="text/xsl"?>
<!--<!DOCTYPE dialog SYSTEM	"dialog.dtd">-->
<dialog skin='light' defbtn='okay' debug='true'>
	<field name='poison' top='53' left='206' width='52' height='16'/>
	<field name='breath-str' top='77' left='206' width='52' height='16'/>
	<field name='abil-xtra' top='204' left='382' width='53' height='17'/>
	<field name='loot-item' top='246' left='194' width='64' height='16'/>
	<field name='loot-chance' top='247' left='464' width='64' height='16'/>
	<button name='okay' type='regular' top='325' left='572'>OK</button>
	<button name='cancel' type='regular' top='325' left='506'>Cancel</button>
	<!--
	 TODO: Originally these LED labels would've been bold, I think
	 Note: These LEDs were shifted left 100 pixels to account for the labels swapping sides
	 -->
	<group name='breath-type'>
		<led name='fire' state='off' top='82' left='394' width='100'>Fire</led>
		<led name='cold' state='off' top='97' left='394' width='100'>Cold</led>
		<led name='shock' state='off' top='112' left='394' width='100'>Electricity</led>
		<led name='dark' state='off' top='127' left='394' width='100'>Darkness</led>
	</group>
	<led name='magic-res' state='off' top='283' left='167' width='100'>Resist Magic</led>
	<led name='fire-res' state='off' top='298' left='167' width='100'>Resist Fire</led>
	<led name='cold-res' state='off' top='313' left='167' width='100'>Resist Cold</led>
	<led name='poison-res' state='off' top='328' left='167' width='100'>Resist Poison</led>
	<led name='magic-imm' state='off' top='283' left='320' width='100'>Immune To Magic</led>
	<led name='fire-imm' state='off' top='298' left='320' width='100'>Immune To Fire</led>
	<led name='cold-imm' state='off' top='313' left='320' width='100'>Immune To Cold</led>
	<led name='poison-imm' state='off' top='328' left='320' width='100'>Immune To Poison</led>
	<pict type='dlog' num='16' top='8' left='8'/>
	<text size='large' top='6' left='50' width='158' height='16'>Edit Monster Abilities</text>
	<text framed='true' top='6' left='222' width='111' height='14'>Monster number:</text>
	<text name='num' framed='true' top='8' left='340' width='37' height='14'/>
	<text top='2' left='408' width='184' height='54'>
		Enter properties for this monster type. For a detailed
		description of the fields, see the documentation.
	</text>
	<text top='54' left='7' width='179' height='14'>Monster Poison: (0 - 8)</text>
	<text top='77' left='7' width='190' height='68'>Monster Breath Weapon strength (0 - 40):</text>
	<text top='78' left='268' width='131' height='14'>Breath weapon type:</text>
	<text size='large' top='152' left='7' width='120' height='14'>Special ability:</text>
	<text name='abil-name' framed='true' top='152' left='184' width='183' height='14'/>
	<button name='abils' type='regular' top='149' left='374'>Choose</button>
	<text size='large' top='178' left='7' width='166' height='15'>Create monsters/fields:</text>
	<text name='radiate-name' framed='true' top='178' left='184' width='183' height='14'/>
	<button name='radiate' type='regular' top='175' left='374'>Choose</button>
	<text top='205' left='54' width='118' height='16'/>
	<text name='radiate-param' framed='true' top='205' left='180' width='195' height='14'/>
	<text size='large' top='228' left='7' width='158' height='16'>Special treasure:</text>
	<text top='247' left='23' width='162' height='14'>Item to drop when killed:</text>
	<text top='247' left='270' width='186' height='14'>Chance of dropping: (0-100)</text>
	<text top='279' left='9' width='141' height='14'>Monster resistances:</text>
	<!--
	 Note: These LEDs were shifted left 80 pixels to account for the labels swapping sides
	 -->
	<group name='summon'>
		<led name='s0' state='off' top='153' left='525' width='100'>No Summon</led>
		<led name='s1' state='off' top='168' left='525' width='100'>Type 1</led>
		<led name='s2' state='off' top='183' left='525' width='100'>Type 2</led>
		<led name='s3' state='off' top='198' left='525' width='100'>Type 3</led>
	</group>
	<text top='149' left='440' width='94' height='14'>Summon type:</text>
</dialog>

=== AdrashaVaux/cboe/rsrc/dialogs/preferences.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<?xml-stylesheet href="dialog.xsl" type="text/xsl"?>
<!--<!DOCTYPE dialog SYSTEM	"dialog.dtd">-->
<dialog skin='dark' defbtn='okay'>
	<!--
	 TODO: All the LEDs here should have bold labels according to the original DITL; do they get that by default? The XSL transformation with CSS stylesheet doesn't give them bold labels.
	 TODO: This dialog is very disorganized; rearrange stuff to be in order
	 -->
	<button name='okay' type='regular' top='426' left='354'>OK</button>
	<button name='cancel' type='regular' def-key='esc' top='426' left='281'>Cancel</button>
	<text framed='true' top='48' left='64' width='277' height='102'/>
	<group name='display'>
		<led name='mid' top='88' left='147' width='75'>Center</led>
		<led name='tl' top='55' left='72' width='54'>Top Left</led>
		<led name='tr' top='55' left='213' width='62'>Top Right</led>
		<led name='bl' top='126' left='72' width='104'>Bottom Left</led>
		<led name='br' top='126' left='213' width='104'>Bottom Right</led>
		<led name='win' top='159' left='66' width='228'>Small Window (not full screen)</led>
	</group>
	<text size='large' top='25' left='59' width='182' height='17'>Display alignment:</text>
	<text size='large' top='6' left='49' width='218' height='16'>
		Blades of Exile Preferences:
	</text>
	<led name='nomaps' top='309' left='53' width='120'>Don't Save Maps</led>
	<led name='nosound' top='307' left='228' width='117'>No Sounds</led>
	<led name='nofrills' top='244' left='53' width='335'>No graphics frills (lose special effects)</led>
	<led name='repeatdesc' top='329' left='53' width='287'>Show room descriptions more than once</led>
	<pict type='dlog' num='16' top='8' left='8'/>
	<led name='nohelp' top='349' left='53' width='306'>Never show instant help</led>
	<led name='resethelp' top='369' left='53' width='340'>
		Reset instant help (all help windows will reappear)
	</led>
	<text size='large' top='181' left='54' width='182' height='17'>Game speed:</text>
	<group name='speed'>
		<led name='fast' top='202' left='69' width='53'>Fast</led>
		<led name='med' top='202' left='151' width='53'>Medium</led>
		<led name='slow' top='202' left='244' width='53'>Slow</led>
		<led name='snail' top='202' left='328' width='70'>Quite Slow</led>
	</group>
	<led name='easier' top='389' left='53' width='352'>Make game easier (monsters much weaker)</led>
	<led name='lesswm' top='409' left='53' width='340'>Fewer wandering monsters</led>
	<text size='large' top='221' left='54' width='182' height='17'>For older machines:</text>
	<led name='noanim' top='264' left='53' width='335'>Turn off terrain animation</led>
	<led name='noshore' top='284' left='53' width='335'>Turn of frills on shore</led>
</dialog>
