=== AdrashaVaux/cboe/rsrc/schemas/dialog.dtd
<!ELEMENT dialog ((field | text | pict | button | led | group | stack)*)>
<!ELEMENT field EMPTY>
<!ELEMENT br EMPTY>
<!ELEMENT text (#PCDATA|br)*>
<!ELEMENT pict EMPTY>
<!ELEMENT key EMPTY>
<!ELEMENT button (#PCDATA|key)*>
<!ELEMENT led (CDATA)>
<!ELEMENT group (led+)>
<!ELEMENT stack ((field | text | pict | button | led | group)*)>

<!ENTITY % num '(NUMBER)'>
<!ENTITY % bool '(true|false)'>
<!ENTITY % picttype '(blank|ter|teranim|monst|dlog|talk|scen|item|pc|field|boom|missile|full|map|status)'>
<!ENTITY % btntype '(small|regular|large|help|left|right|up|down|tiny|done|tall|trait|push)'>
<!ENTITY % letter 'a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z'>
<!ENTITY % mod 'ctrl|shift|alt'>
<!ENTITY % key '%mod;|%letter;|left|right|up|down|esc|enter|return|tab|help|space'>
<!ENTITY % rect '
	top			%num;						#REQUIRED
	left		%num;						#REQUIRED
	width		%num;						#IMPLIED
	height		%num;						#IMPLIED
'>
<!ENTITY % font "
	font		(dungeon|geneva|silom|maidenword)	'silom'
	size		(small|large)				'small'
	color		CDATA						#IMPLIED
	colour		CDATA						#IMPLIED
">

<!ATTLIST dialog
	skin		(light|dark)				'dark'
	debug		%bool;						'false'
	fore		CDATA						'black'
	defbtn		IDREF						#IMPLIED
>
<!ATTLIST field
	name		ID							#IMPLIED
	type		(num|text)					'text'
	%rect;
>
<!ATTLIST text
	name		ID							#IMPLIED
	framed		%bool;						'true'
	%font;
	def-key		(%key;|none)				'none'
	clickable	%bool;						'false'
	fromlist	(none|CDATA)				'none'
	%rect;
>
<!ATTLIST pict
	name		ID							#IMPLIED
	type		%picttype;					#REQUIRED
	custom		%bool;						'false'
	size		(small|wide|tall|large)		#IMPLIED
	def-key		(%key;|none)				'none'
	clickable	%bool;						'false'
	num			%num;						#REQUIRED
	%rect;
>
<!ATTLIST button
	name		ID							#REQUIRED
	type		%btntype;					#REQUIRED
	wrap		%bool;						'false'
	def-key		(%key;|none)				'none'
	fromlist	(none|CDATA)				'none'
	%rect;
>
<!ATTLIST led
	name		ID							#IMPLIED
	state		(red|green|off)				'off'
	fromlist	(none|CDATA)				'none'
	%rect;
	%font;
>
<!ATTLIST group
	name		ID							#IMPLIED
	fromlist 	(none|CDATA)				'none'
>
<!ATTLIST stack
	name		ID							#IMPLIED
>

=== AdrashaVaux/cboe/rsrc/dialogs/pick-race-abil.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<?xml-stylesheet href="dialog.xsl" type="text/xsl"?>
<!--<!DOCTYPE dialog SYSTEM	"dialog.dtd">-->
<dialog skin='dark' defbtn='done'>
	<!--
	 TODO: Why are all the percent signs backwards?
	 -->
	<text size='large' top='9' left='55' width='181' height='16'>Special Characteristics:</text>
	<pict type='dlog' num='7' top='6' left='6'/>
	<button name='done' type='done' top='349' left='423'/>
	<!--
	 TODO: Move the LED labels into the LED elements
	 TODO: Originally these LED labels would've been bold
	 NOTE: All LED widths had 18 added to the width of the label
	 -->
	<group name='race'>
		<led name='race1' state='off' top='55' left='161' width='75'/>
		<led name='race2' state='off' top='55' left='289' width='75'/>
		<led name='race3' state='off' top='55' left='447' width='92'/>
		<!--
		 TODO: Add Vahnatai
		 <led name='race4' state='off' top='55' left='605' width='92'/>
		 -->
	</group>
	<led name='good1' state='off' top='97' left='215' width='75'/>
	<led name='good2' state='off' top='112' left='215' width='75'/>
	<led name='good3' state='off' top='127' left='215' width='116'/>
	<led name='good4' state='off' top='142' left='215' width='75'/>
	<led name='good5' state='off' top='157' left='215' width='75'/>
	<led name='good6' state='off' top='97' left='416' width='126'/>
	<led name='good7' state='off' top='112' left='416'/>
	<led name='good8' state='off' top='127' left='416'/>
	<led name='good9' state='off' top='142' left='416'/>
	<led name='good10' state='off' top='157' left='416'/>
	<text size='large' top='30' left='55' width='65' height='18'>Species:</text>
	<text name='xp' framed='true' top='352' left='254' width='50' height='16'/>
	<text name='info' framed='true' top='282' left='15' width='300' height='59'>Select species and traits.</text>
	<!--
	 TODO: If it looks wrong in-game, try reverting to original label widths.
	 Original label widths were: 75 75 92 75 75 116 75 75 126 116 75 75 126
	 -->
	<text top='53' left='55' width='126' height='16'>Human (0%)</text>
	<text top='53' left='186' width='126' height='16'>Nephilim (%12)</text>
	<text top='53' left='316' width='126' height='16'>Slithzerikai (%20)</text>
	<!--
	 TODO: Add Vahnatai
	 <text top='53' left='474' width='126' height='16'>Vahnatai (22%)</text>
	 -->
	<text top='95' left='55' width='126' height='16'>Toughness (%10)</text>
	<text top='110' left='55' width='126' height='16'>Magically Apt. (%20)</text>
	<text top='125' left='55' width='126' height='16'>Ambidextrous (%8)</text>
	<text top='140' left='55' width='126' height='16'>Nimble Fingers (%10)</text>
	<text top='155' left='55' width='126' height='16'>Cave Lore (%4)</text>
	<text top='95' left='236' width='126' height='16'>Woodsman (%6)</text>
	<text top='197' left='55' width='126' height='16'>Sluggish (%-10)</text>
	<text top='212' left='55' width='126' height='16'>Magically Inept (%-8)</text>
	<text top='227' left='55' width='126' height='16'>Frail (%-8)</text>
	<text top='242' left='55' width='126' height='16'>Chronic Disease (%-20)</text>
	<text top='352' left='19' width='216' height='16'>Experience needed to gain each level:</text>
	<!-- Original widths were: 75 75 -->
	<text size='large' top='74' left='55' width='126' height='16'>Advantages:</text>
	<text size='large' top='178' left='55' width='126' height='16'>Disadvantages</text>
	<led name='bad1' state='off' top='198' left='237'/>
	<led name='bad2' state='off' top='213' left='237'/>
	<led name='bad3' state='off' top='228' left='237'/>
	<led name='bad4' state='off' top='243' left='237'/>
	<led name='bad5' state='off' top='258' left='237'/>
	<!--
	 TODO: Add Pacifist
	 <led name='bad6' state='off' top='273' left='237'/>
	 -->
	<!-- Original label widths were: 126 126 126 126 126 -->
	<text top='110' left='236' width='136' height='16'>Good Constitution (%10)</text>
	<text top='125' left='236' width='136' height='16'>Highly Alert (%7)</text>
	<text top='140' left='236' width='200' height='16'>Exceptional Strength (%12)</text>
	<text top='155' left='236' width='136' height='16'>Recuperation (%15)</text>
	<text top='257' left='55' width='136' height='16'>Bad Back (%-8)</text>
	<!--
	 TODO: Add Pacifist
	 <text top='272' left='55' width='136' height='16'>Pacifist (-40%)</text>
	 -->
	<text top='223' left='289' width='204' height='43'>Number in () is how much having that trait affects the experience you need to gain a level.</text>
</dialog>

=== AdrashaVaux/cboe/rsrc/dialogs/edit-monster.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<?xml-stylesheet href="dialog.xsl" type="text/xsl"?>
<!--<!DOCTYPE dialog SYSTEM	"dialog.dtd">-->
<dialog skin='light' defbtn='okay' debug='true'>
	<field name='name' top='30' left='180' width='186' height='16'/>
	<field name='pic' top='57' left='140' width='52' height='16'/>
	<field name='level' top='82' left='206' width='52' height='16'/>
	<field name='health' top='106' left='206' width='52' height='16'/>
	<field name='armor' top='130' left='206' width='52' height='16'/>
	<field name='skill' top='154' left='206' width='52' height='16'/>
	<field name='speed' top='178' left='206' width='52' height='16'/>
	<field name='mage' top='202' left='206' width='51' height='16'/>
	<field name='priest' top='226' left='206' width='51' height='16'/>
	<field name='dice1' top='101' left='501' width='52' height='16'/>
	<field name='sides1' top='125' left='501' width='52' height='16'/>
	<field name='dice2' top='149' left='501' width='52' height='16'/>
	<field name='sides2' top='173' left='501' width='52' height='16'/>
	<field name='dice3' top='197' left='501' width='52' height='16'/>
	<field name='sides3' top='221' left='501' width='52' height='16'/>
	<field name='talk' top='327' left='168' width='77' height='16'/>
	<field name='treas' top='273' left='513' width='55' height='16'/>
	<button name='okay' type='regular' top='418' left='512'>OK</button>
	<button name='cancel' type='regular' def-key='esc' top='418' left='439'>Cancel</button>
	<button name='left' type='left' def-key='left' top='388' left='335'/>
	<button name='right' type='right' def-key='right' top='388' left='398'/>
	<button name='abils' type='large' top='388' left='473'>Abilities</button>
	<button name='pickicon' type='large' top='53' left='201'>Select Icon</button>
	<button name='picktype' type='regular' top='250' left='264'>Choose</button>
	<button name='picktype1' type='regular' top='275' left='264'>Choose</button>
	<button name='picktype2' type='regular' top='300' left='264'>Choose</button>
	<button name='picktalk' type='regular' top='326' left='264'>Choose</button>
	<group name='attitude'>
		<led name='docile' top='355' left='358' width='100'>Friendly, Docile</led>
		<led name='A' top='370' left='358' width='100'>Hostile, Type A</led>
		<led name='friendly' top='355' left='490' width='100'>Friendly, Will Fight</led>
		<led name='B' top='370' left='490' width='100'>Hostile, Type B</led>
	</group>
	<text name='num' top='8' left='334' width='37' height='14'/>
	<pict name='icon' type='monst' num='0' top='8' left='8'/>
	<text size='large' top='6' left='44' width='158' height='16'>Edit Monster Statistics</text>
	<text top='8' left='216' width='111' height='16'>Monster number:</text>
	<text top='390' left='4' width='294' height='54'>
		Enter properties for this monster type.
		For a detailed description of the fields, see the documentation.
		To edit monsterâ€™s special abilities, press the Edit Abilities button.
	</text>
	<text top='31' left='44' width='120' height='14'>Monster type name:</text>
	<text top='58' left='8' width='120' height='14'>Monster picture:</text>
	<text name='w' top='59' left='334' width='86' height='14'>Width = </text>
	<text name='h' top='59' left='426' width='86' height='14'>Height = </text>
	<text name='type' top='253' left='134' width='120' height='14'/>
	<text name='type1' top='278' left='134' width='120' height='14'/>
	<text name='type2' top='303' left='134' width='120' height='14'/>
	<text top='253' left='8' width='120' height='14'>Monster type:</text>
	<text top='278' left='8' width='120' height='14'>Attack 1 type:</text>
	<text top='303' left='8' width='120' height='14'>Attack #2,3 type:</text>
	<text top='329' left='8' width='152' height='14'>Default talking picture:</text>
	<!-- Note: This originally had width=202 -->
	<text top='352' left='8' width='302' height='14'>Default attitude:
		(attitude creature has when you place it)
	</text>
	<text size='large' top='250' left='343' width='158' height='16'>Treasure:</text>
	<text top='275' left='343' width='162' height='14'>Monster treasure: (0-4)</text>
	<text top='83' left='8' width='179' height='14'>Monster level: (0 - 40)</text>
	<text top='107' left='8' width='179' height='14'>Monster health: (0 - 2500)</text>
	<text top='131' left='8' width='179' height='14'>Monster armor: (0 - 50)</text>
	<text top='155' left='8' width='179' height='14'>Monster skill: (0 - 40)</text>
	<text top='179' left='8' width='179' height='14'>Monster speed: (1-12)</text>
	<text top='203' left='8' width='179' height='14'>Monster magic spells: (0 - 7)</text>
	<text top='227' left='8' width='179' height='14'>Monster priest spells: (0 - 7)</text>
	<text size='large' top='82' left='273' width='158' height='16'>Hand to hand combat:</text>
	<text top='102' left='283' width='214' height='14'>Attack 1 number of dice: (0 - 20)</text>
	<text top='126' left='283' width='214' height='14'>Attack 1 number of sides: (1-50)</text>
	<text top='150' left='283' width='214' height='14'>Attack 2 number of dice: (0 - 20)</text>
	<text top='174' left='283' width='214' height='14'>Attack 2 number of sides: (1-50)</text>
	<text top='198' left='283' width='214' height='14'>Attack 3 number of dice (0 - 20)</text>
	<text top='222' left='283' width='214' height='14'>Attack 3 number of sides: (1-50)</text>
</dialog>

=== AdrashaVaux/cboe/rsrc/dialogs/edit-item.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<?xml-stylesheet href="dialog.xsl" type="text/xsl"?>
<!--<!DOCTYPE dialog SYSTEM	"dialog.dtd">-->
<dialog skin='light' defbtn='okay' debug='true'>
	<!--
	 TODO: Assign numeric types (type = 'int' or 'uint') to fields as appropriate
	 -->
	<field name='full' top='30' left='163' width='126' height='16'/>
	<field name="short" top='30' left='458' width='125' height='16'/>
	<field name='picnum' top='62' left='140' width='52' height='16'/>
	<field name='level' top='199' left='161' width='52' height='16'/>
	<field name='awkward' top='223' left='161' width='52' height='16'/>
	<field name='bonus' top='247' left='161' width='52' height='16'/>
	<field name='prot' top='271' left='161' width='52' height='16'/>
	<field name='charges' top='295' left='161' width='52' height='16'/>
	<field name='flag' top='199' left='366' width='52' height='16'/>
	<field name='value' top='223' left='366' width='52' height='16'/>
	<field name='weight' top='247' left='366' width='52' height='16'/>
	<field name='class' top='271' left='366' width='52' height='16'/>
	<button name='okay' type='regular' top='337' left='509'>OK</button>
	<button name='cancel' type='regular' top='337' left='434' def-key='esc'>Cancel</button>
	<button name='prev' type='left' top='337' left='13'/>
	<button name='next' type='right' top='337' left='76'/>
	<!--
	 NOTE: All these LEDs have been shifted 100 pixels left to account for the labels swapping sides
	 -->
	<group name='variety'>
		<led name='none' state='off' top='89' left='106' width='90'>No Item</led>
		<led name='weap1' state='off' top='104' left='106' width='90'>1-Handed weapon</led>
		<led name='weap2' state='off' top='119' left='106' width='90'>2-Handed weapon</led>
		<led name='gold' state='off' top='134' left='106' width='90'>Gold</led>
		<led name='bow' state='off' top='149' left='106' width='90'>Bow</led>
		<led name='arrow' state='off' top='164' left='106' width='90'>Arrows</led>
		<led name='thrown' state='off' top='179' left='106' width='90'>Thrown missile</led>
		<led name='potion' state='off' top='89' left='218' width='90'>Potion/Magic Item</led>
		<led name='scroll' state='off' top='104' left='218' width='90'>Scroll/Magic Item</led>
		<led name='wand' state='off' top='119' left='218' width='90'>Wand</led>
		<led name='tool' state='off' top='134' left='218' width='90'>Tool</led>
		<led name='food' state='off' top='149' left='218' width='90'>Food</led>
		<led name='shield' state='off' top='164' left='218' width='90'>Shield</led>
		<led name='armor' state='off' top='179' left='218' width='90'>Armor</led>
		<led name='helm' state='off' top='89' left='336' width='90'>Helm</led>
		<led name='gloves' state='off' top='104' left='336' width='90'>Gloves</led>
		<!--
		 TODO: Why are there two shields?
		 -->
		<led name='shield2' state='off' top='119' left='336' width='90'>Shield</led>
		<led name='boots' state='off' top='134' left='336' width='90'>Boots</led>
		<led name='ring' state='off' top='149' left='336' width='90'>Ring</led>
		<led name='necklace' state='off' top='164' left='336' width='90'>Necklace</led>
		<led name='poison' state='off' top='179' left='336' width='90'>Weapon Poison</led>
		<led name='nonuse' state='off' top='89' left='448' width='90'>Non-Use Object</led>
		<led name='pants' state='off' top='104' left='448' width='90'>Pants</led>
		<led name='xbow' state='off' top='119' left='448' width='90'>Crossbow</led>
		<led name='bolt' state='off' top='134' left='448' width='90'>Bolts</led>
		<led name='missile' state='off' top='149' left='448' width='90'>Missile (no ammo)</led>
		<led name='unused1' state='off' top='164' left='448' width='90'>Unused</led>
		<led name='unused2' state='off' top='179' left='448' width='80'>Unused</led>
	</group>
	<!--
	 NOTE: These LEDs have been shifted 80 pixels left to account for the labels swapping sides
	 -->
	<group name='melee-type'>
		<led name='edge' state='off' top='233' left='442' width='80'>Edged</led>
		<led name='bash' state='off' top='248' left='442' width='80'>Bashing</led>
		<led name='pole' state='off' top='263' left='442' width='80'>Pole</led>
	</group>
	<pict name="pic" type='dlog' num='16' top='8' left='11'/>
	<text size='large' top='6' left='50' width='158' height='16'>Edit an Item Type</text>
	<text top='8' left='222' width='111' height='14'>Item number:</text>
	<text name='num' top='8' left='340' width='37' height='14'/>
	<text top='31' left='50' width='107' height='14'>Item Full Name:</text>
	<text top='31' left='298' width='155' height='14'>Item Unidentified Name:</text>
	<text top='63' left='8' width='120' height='14'>Item picture:</text>
	<button name="choosepic" type='large' top='58' left='201'>Select Icon</button>
	<text size='large' top='87' left='8' width='86' height='16'>Item type:</text>
	<text top='200' left='8' width='148' height='14'>Item level: (0 - 50)</text>
	<text top='224' left='8' width='148' height='14'>Awkwardness: (0-20)</text>
	<text top='248' left='8' width='148' height='14'>Bonus: (0-10)</text>
	<text top='272' left='8' width='148' height='14'>Protection: (-10 - 20)</text>
	<text top='296' left='8' width='148' height='14'>Charges: (0-100)</text>
	<text top='200' left='220' width='137' height='13'>Type flag: (0-1000)</text>
	<text top='224' left='220' width='141' height='13'>Value: (0-10000)</text>
	<text top='248' left='220' width='141' height='13'>Weight: (0-250)</text>
	<text top='272' left='220' width='141' height='13'>Special class: (0-100)</text>
	<text top='200' left='425' width='161' height='28'>Weapon type: (ignored if not a weapon)</text>
	<text top='293' left='221' width='363' height='40'>
		Enter properties for this item type. 
		For a detailed description of the fields, see the documentation. 
		Click Edit Abilities to edit item abilities.
	</text>
	<button name="abils" type='large' top='337' left='155'>Abilities</button>
</dialog>
